version: "3"
services:
  frontend:
    container_name: typingApp_frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:80

volumes:
  node-packages:
    external: false

networks:
  default:
    external: false
