version: "3"
services:
  frontend:
    container_name: typingApp_frontend
    # ここで指定した階層外のファイルは指定できない
    build:
      context: ./
    ports:
      - 3001:80

volumes:
  node-packages:
    external: false

networks:
  default:
    external: false
